name: Python Web Backend

on:
  workflow_dispatch:  

jobs:
  run-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Start backend server
      run: |
        nohup python app.py &  # Démarre l'application Flask en arrière-plan
        sleep 5                 # Attend que le serveur démarre

    - name: Test adding and searching a card
      run: |
        curl -X POST http://localhost:5000/add_card -H "Content-Type: application/json" -d '{"name": "Test Card", "serial_number": "12345", "card_type": "Type1"}'
        curl http://localhost:5000/search_card?search_term=12345
