name: Python Web Backend

on:
  workflow_dispatch:  

jobs:
  run-backend:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Start backend server
      run: |
        pip python app.py &  # Démarre l'application Flask en arrière-plan
        sleep 5                 # Attend que le serveur démarre

   
